# Generated by Django 5.1.7 on 2025-04-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='details',
            name='clinic_name',
        ),
    ]
