# Generated by Django 5.1.7 on 2025-04-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='username',
        ),
    ]
