# Generated by Django 5.1.7 on 2025-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_details_clinic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='address',
            field=models.CharField(default='Default Address', max_length=30),
        ),
        migrations.AlterField(
            model_name='vet',
            name='city',
            field=models.CharField(default='Default City', max_length=30),
        ),
        migrations.AlterField(
            model_name='vet',
            name='clinic_name',
            field=models.CharField(default='Default Clinic', max_length=100),
        ),
        migrations.AlterField(
            model_name='vet',
            name='zip_code',
            field=models.CharField(default='00000', max_length=30),
        ),
    ]
