# Generated by Django 5.1.7 on 2025-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_details_firstname_remove_details_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='details',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='role',
            field=models.CharField(choices=[('v', 'vet'), ('o', 'owner'), ('a', 'admin')], default='o', max_length=1),
        ),
    ]
