# render.yaml in your repo root
services:
  - type: web
    name: pet-health-manager
    runtime: python
    repo: https://github.com/h-koehler/PetHealthManager
    branch: render-deployment
    plan: free
    region: virginia
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DEBUG
        sync: false
      - key: SECRET_KEY
        sync: false

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput \
        && python manage.py loaddata p6.json \
        && gunicorn djangoProject.wsgi:application

    autoDeployTrigger: "off"