# Generated by Django 5.1.7 on 2025-04-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items_created_by', to='pets.user'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='feed_type',
            field=models.CharField(choices=[('gen', 'General Update'), ('inq', 'Inquiry to Vet')], default='gen', max_length=3),
        ),
        migrations.AddField(
            model_name='pet',
            name='nonOwners',
            field=models.ManyToManyField(related_name='pets_as_sitters', to='pets.user'),
        ),
    ]
