# Generated by Django 5.1.7 on 2025-04-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedItem',
        ),
    ]
