# Generated by Django 5.1.7 on 2025-04-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_delete_feeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='next_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
