# Generated by Django 5.1.7 on 2025-04-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20250413_0116'),
    ]

    operations = [
    ]
