# Generated by Django 5.1.7 on 2025-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
