# Generated by Django 5.1.7 on 2025-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20250413_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
