# Generated by Django 5.1.7 on 2025-04-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_feeditem_title'),
    ]

    operations = [
    ]
