# Generated by Django 5.1.7 on 2025-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20250413_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
