# Generated by Django 5.1.7 on 2025-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_add_username_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pets_profiles/'),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
