# Generated by Django 5.1.7 on 2025-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_pet_pfp_alter_feeditem_title_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pet_profiles/'),
        ),
    ]
