# Generated by Django 5.1.7 on 2025-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_alter_pet_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nonOwners',
            field=models.ManyToManyField(blank=True, related_name='pets_as_sitters', to='pets.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
