# Generated by Django 5.1.7 on 2025-04-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_alter_pet_owner_alter_pet_vet_and_more'),
        ('users', '0003_remove_details_firstname_remove_details_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='feeditem',
            old_name='isSolved',
            new_name='is_solved',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='nonOwners',
            new_name='non_owners',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='lastDone',
            new_name='last_done',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='nextDue',
            new_name='next_due',
        ),
        migrations.AlterField(
            model_name='pet',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_as_vet', to='users.vet'),
        ),
    ]
