# Generated by Django 5.1.7 on 2025-04-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
